services:
  backend:
    build:
      context: ./backend
    command: ["uv", "run", "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - 8000:8000
    environment:
      - UVICORN_RELOAD=true
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017
    volumes:
      - ./backend:/app:z
    networks:
      - kisee
    depends_on:
      - mongo

  agent:
    build:
      context: ./agent
    command: ["python", "agent_worker.py", "dev"]
    env_file: ./agent/.env
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017
    volumes:
      - ./agent:/home/appuser/app:z
    networks:
      - kisee
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    networks:
      - kisee
    volumes:
      - mongodata:/data/db:z

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8001:8081
    environment:
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    depends_on:
      - mongo
    networks:
      - kisee

volumes:
  mongodata:
networks:
  kisee:
    name: kisee
